apiVersion: app.redislabs.com/v1alpha1
kind: RedisEnterpriseDatabase
metadata:
  name: db
spec:
  redisEnterpriseCluster:
    name: rec
  memorySize: 100MB
  evictionPolicy: noeviction # defaults to volatile-lru
  defaultUser: true
  shardCount: 1
  replication: true
  persistence: "aofAlways"
