apiVersion: v1
kind: Secret
metadata:
  name: rec
type: opaque
stringData:
  username: admin@redis.io
  password: adminRL123
---
apiVersion: "app.redislabs.com/v1"
kind: "RedisEnterpriseCluster"
metadata:
  name: rec
spec:
  nodes: 3
  persistentSpec:
    enabled: true
    # default to 20GB per REC node
  uiServiceType: ClusterIP
  username: "admin@redis.io"
  redisEnterpriseNodeResources:
    limits:
      cpu: "4000m"
      memory: 4Gi
    requests:
      cpu: "200m"
      memory: 4Gi
